CREATE TABLE Department (
	id		INTEGER PRIMARY KEY AUTO_INCREMENT,
	name	VARCHAR(30)
);
CREATE TABLE Employee (
	id			INTEGER PRIMARY KEY AUTO_INCREMENT,
	firstName	VARCHAR(14) NOT NULL,
	lastName	VARCHAR(16) NOT NULL,
	hireDate	DATE NOT NULL,
);
CREATE TABLE DeptEmpl (
	id			INTEGER PRIMARY KEY AUTO_INCREMENT,
	emplId		INTEGER NOT NULL,
	deptId		INTEGER NOT NULL,
	fromDate	DATE NOT NULL,
	toDate		DATE,
	UNIQUE INDEX emplId_deptId (emplId, deptId),
	CONSTRAINT DeptEmpl_Employee_fk FOREIGN KEY (emplId) REFERENCES Employee (id) ON DELETE CASCADE,
	CONSTRAINT DeptEmpl_Department_fk FOREIGN KEY (deptId) REFERENCES Department (id) ON UPDATE CASCADE
);
CREATE TABLE Salary (
	id			INTEGER PRIMARY KEY AUTO_INCREMENT,
	emplId		INTEGER NOT NULL,
	salary		INTEGER NOT NULL,
	fromDate	DATE NOT NULL,
	toDate		DATE,
	CONSTRAINT Salary_Employee_fk FOREIGN KEY (emplId) REFERENCES Employee (id) ON DELETE CASCADE
);